<?php

$labels = array(
	'name'                  => _x( 'Products', 'Post Type General Name', 'inaset-cpt' ),
	'singular_name'         => _x( 'Product', 'Post Type Singular Name', 'inaset-cpt' ),
	'menu_name'             => __( 'Products', 'inaset-cpt' ),
	'name_admin_bar'        => __( 'Products', 'inaset-cpt' ),
	'archives'              => __( 'Products Archives', 'inaset-cpt' ),
	'attributes'            => __( 'Products Attributes', 'inaset-cpt' ),
	'parent_item_colon'     => __( 'Parent Product:', 'inaset-cpt' ),
	'all_items'             => __( 'All Products', 'inaset-cpt' ),
	'add_new_item'          => __( 'Add New Product', 'inaset-cpt' ),
	'add_new'               => __( 'Add New', 'inaset-cpt' ),
	'new_item'              => __( 'New Product', 'inaset-cpt' ),
	'edit_item'             => __( 'Edit Product', 'inaset-cpt' ),
	'update_item'           => __( 'Update Product', 'inaset-cpt' ),
	'view_item'             => __( 'View Product', 'inaset-cpt' ),
	'view_items'            => __( 'View Products', 'inaset-cpt' ),
	'search_items'          => __( 'Search Product', 'inaset-cpt' ),
	'not_found'             => __( 'Not found', 'inaset-cpt' ),
	'not_found_in_trash'    => __( 'Not found in Trash', 'inaset-cpt' ),
	'featured_image'        => __( 'Featured Image', 'inaset-cpt' ),
	'set_featured_image'    => __( 'Set featured image', 'inaset-cpt' ),
	'remove_featured_image' => __( 'Remove featured image', 'inaset-cpt' ),
	'use_featured_image'    => __( 'Use as featured image', 'inaset-cpt' ),
	'insert_into_item'      => __( 'Insert into Product', 'inaset-cpt' ),
	'uploaded_to_this_item' => __( 'Uploaded to this Product', 'inaset-cpt' ),
	'items_list'            => __( 'Products list', 'inaset-cpt' ),
	'items_list_navigation' => __( 'Products list navigation', 'inaset-cpt' ),
	'filter_items_list'     => __( 'Filter Products list', 'inaset-cpt' ),
);
$rewrite = array(
	'slug'                  => 'product',
	'with_front'            => true,
	'pages'                 => true,
	'feeds'                 => true,
);
$args = array(
	'label'                 => __( 'Products', 'inaset-cpt' ),
	'description'           => '',
	'labels'                => $labels,
	'supports'              => array( 'title', 'editor', 'thumbnail', 'reviews' ),
	'taxonomies'            => array( '' ),
	'hierarchical'          => false,
	'public'                => true,
	'show_ui'               => true,
	'show_in_menu'          => true,
	'menu_icon'             => 'dashicons-cart',
	'menu_position'         => 21,
	'show_in_admin_bar'     => false,
	'show_in_nav_menus'     => true,
	'can_export'            => true,
	'has_archive'           => false,
	'exclude_from_search'   => false,
	'publicly_queryable'    => true,
	'rewrite'               => $rewrite,
	'capability_type'       => 'page',
	'show_in_rest'          => false,
);

register_post_type( 'product', $args );
